### ISSUE TITLE
"certbot renew" should not stop/start Chef Automate 

### ISSUE THREAD

**Issue by stuartpreston** [chef-partners/azure-managed-automate#56]
Currently, cron tasks stop Chef Automate before renewing certificates - this is stopped by a pre-hook to `certbot renew`.  If there is a failure running certbot (e.g. no DNS) then Chef Automate will not be started up again.

Talking to support, we "should be able to apply that through a config patch and then it would only need to restart the gateway service" - I guess if the filenames are different. If not then we can just restart the gateway service, avoiding expensive operation restarting Elasticsearch.

Desired fix: Update script files, embedded cron task, provide instructions to update running instances manually

TBD

**Comment by russellseymour** [comment]
In order to use CertBot it needs to spin up a HTTP server for itself to verify the DNS record to the host it is sitting on. This means that the NGINX service running under Automate needs to be stopped to do this.

I have not been able to find a way to just turn off NGINX without stopping all of Automate. However I am already using the gateway to add in the cert once it has been obtained.

**Comment by stuartpreston** [comment]
Closing this: the pre-hook to stop Chef Automate only fires when there is a new certificate to renew, so the impact of this is much lower than originally reported.
